####Questions 1:
Create a string named str_var and assign the value 'ML is awesome' to the variable and print the variable.

```
# This is formatted as code
```

In [0]:
str_var ="ML is awesome"
print(str_var)

ML is awesome


####Question 2:
Print the second last element of the above created variable.

In [0]:
print(str_var[11]) #From left to right 
print(str_var[-2]) #From right to left

m
m


####Question 3:
Perform #Addition operations on strings mentioned below and print them with and without space.

In [0]:
a = "tom"
b = "haverford"
print(a+b)
print(a + " " + b)

tomhaverford
tom haverford


####Question 4:
Write code to ask the user to enter 3 numbers (a,b,c) and then these values are passed on to a function called **find_largest(a,b,c)** which does some comparison operations (using python comparison operators) between these three numbers and print the result

In [0]:
def find_largest(number1, number2, number3):  
    if number1 >= number2 and number1 >= number3:  
        print(f"{number1} is the biggest number")  
    elif number2 >= number1 and number2 >= number3:  
        print(f"{number2} is the biggest number")  
    else:  
        print(f"{number3} is the biggest number")

In [0]:
number1 = input("Enter Number ")
number2 = input("Enter Number ")
number3 = input("Enter Number ")
print("Number 1 is: " + number1)
print("Number 2 is: " + number2)
print("Number 3 is: " + number3)

Enter Number  1

Enter Number  4

Enter Number  7

Number 1 is: 1
Number 2 is: 4
Number 3 is: 7


In [0]:
find_largest(number1, number2, number3)

7 is the biggest number


####Question 5:
Create a class named car to store the information model,manufactures and year

In [0]:
class car:
  def __init__(self, model, manufacturer, year):
      self.model = model
      self.manufacturer = manufacturer
      self.year = year

####Question 6:
Create an object of the class and print informations mentioned in the above question

In [0]:
car1 = car("Yaris", "Toyota", 2016)
car2 = car("Up", "VW", 2016)

print(car1.model)
print(car1.manufacturer)
print(car1.year)

Yaris
Toyota
2016


####Question 7:
Write a python class called "Employee" with four attributes - name, base_salary, bonus, travel_allowance, with a parameterized constructor to initialize these values and another function called print_total_salary which just adds up the base_salary with bonus and travel_allowance and prints it.

After you define this class, create two or three objects of this class type, say emp1, emp2 and emp3 like this -

```
emp1 = Employee("Tom",1000,300,100)
emp2 = Employee("Dick",2000,600,100)
emp3 = Employee("Harry",500,100,50)
```

And then print the total salaries by accessing the print_total_salary method -

```
emp1.print_total_salary()
emp2.print_total_salary()
emp3.print_total_salary()
```

In [0]:
class Employee:  
    def __init__(self, name, base_salary, bonus, travel_allowance):  
        self.name = name  
        self.base_salary = base_salary  
        self.bonus = bonus  
        self.travel_allowance = travel_allowance  
  
    def print_total_salary(self):  
        total_salary = self.base_salary + self.bonus + self.travel_allowance  
        print(f"The total salary for {self.name} is: {total_salary}")  

In [0]:
# Creating objects of the Employee class  
emp1 = Employee("Tom", 1000, 300, 100)  
emp2 = Employee("Dick", 2000, 600, 100)  
emp3 = Employee("Harry", 500, 100, 50) 

In [0]:
# Printing the total salaries  
emp1.print_total_salary() #Print Tom
emp2.print_total_salary() #Print Dick
emp3.print_total_salary() #Print Harry

The total salary for Tom is: 1400
The total salary for Dick is: 2700
The total salary for Harry is: 650


#### Question 8: 
Create a One-dimensional array of size 9 with a range of 15 random elements. Create a Two-dimensional array with 3 rows and 4 columns inside the range of 15 random elements. Create a Three-dimensional array of 3 arrays with 4 rows and 5 columns with a range of 15 random elements.


In [0]:
import numpy as np

np.random.seed(1) #Assigned a number to generate same results each time.
ar1 = np.random.randint(15,size=9)
ar2 = np.random.randint(15,size=(3,4))
ar3 = np.random.randint(15, size=(3, 4, 5))

In [0]:
print("1 Dimensional Array")
print(ar1)
print("Shape:", ar1.shape)
print("Size:", ar1.size)
print("Number of dimensions:", ar1.shape)

1 Dimensional Array
[ 5 11 12  8  9 11  5  0  0]
Shape: (9,)
Size: 9
Number of dimensions: (9,)


In [0]:
print("2 Dimensional Array")
print(ar2)
print("Shape:", ar2.shape)
print("Size:", ar2.size)
print("Number of dimensions:", ar2.shape)

2 Dimensional Array
[[ 1 12  7 13]
 [12  6  9  2]
 [ 4 14  5  2]]
Shape: (3, 4)
Size: 12
Number of dimensions: (3, 4)


In [0]:
print("3 Dimensional Array")
print(ar3)
print("Shape:", ar3.shape)
print("Size:", ar3.size)
print("Number of dimensions:", ar3.shape)

3 Dimensional Array
[[[ 4 11 12 10 12]
  [13 14  2  4  7]
  [ 7  9  1  7 14]
  [ 0  6 13  9  9]]

 [[ 7 13  6  9  1]
  [ 0 12  1  8  8]
  [13  3 10  9  8]
  [14  7  3  6  5]]

 [[ 1  9  3  4  8]
  [ 1 11 12 10  4]
  [ 0 13  3  9  2]
  [ 0  4  9  2  7]]]
Shape: (3, 4, 5)
Size: 60
Number of dimensions: (3, 4, 5)


####Question 9:
Write a code to print the values stored in an integer list but use excemption handling in case the user tries to print a value from a position in the list that does not have a value

In [0]:
# Creation of integer list
integer_list = [1, 2, 3, 4, 5]

try:
  # Index from the user
  index = int(input("Enter the index of the value: "))

  # Print the value at the specified index
  print(f"The value at index {index} is: {integer_list[index]}")
except IndexError:
  # Print an error message if the index is out of range
  print(f"Index {index} is out of range.")

Enter the index of the value:  3

The value at index 3 is: 4
